version: "3"
services:
  
  node-app:
    build: .
    volumes:
    - ./:/app
    - /app/node_modules 
    ports:
    - 4000:4000
    env_file: ./.env
  
  mongo:
    image: mongo
    ports:
    - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nelson
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
      - MONGO_INITDB_DATABASE=subscribe_project
    volumes:
      - mongo-db:/data/
  mongo-express:
   image: mongo-express:0.54.0
   depends_on:
    - mongo
   ports:
    - "8080:8081"
   environment:
   - ME_CONFIG_MONGODB_ADMINUSERNAME=nelson
   - ME_CONFIG_MONGODB_ADMINPASSWORD=mypassword
   - ME_CONFIG_MONGODB_SERVER=mongo
volumes:
 mongo-db:
  driver: local
